{% set name = "bigquery-magics" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 3622166a6b30da371bdcd3218be70e905c14975628591d5be90133278acd1384

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - db-dtypes >=0.3.0,<2.0.0
    - google-cloud-bigquery-core >=3.13.0,<4.0.0
    - ipywidgets >=7.7.1
    - ipython >=7.23.1
    - ipykernel >=5.5.6
    - packaging >=20.0.0
    - pandas >=1.2.0
    - pyarrow >=3.0.0
    - pydata-google-auth >=1.5.0
    - tqdm >=4.7.4,<5.0.0

test:
  imports:
    - bigquery_magics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-bigquery-magics
  summary: Google BigQuery magics for Jupyter and IPython
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
