{% set name = "bigquery-magics" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: edce980802b63a02df91b748f4281bab6a7374174733b5e9ae23c136ccd98e82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - db-dtypes >=0.3.0,<2.0.0dev
    - google-cloud-bigquery-core >=3.13.0,<4.0.0dev
    - ipywidgets >=7.7.1
    - ipython >=7.23.1
    - ipykernel >=5.5.6
    - packaging >=20.0.0
    - pandas >=1.1.0
    - pyarrow >=3.0.0
    - pydata-google-auth >=1.5.0
    - tqdm >=4.7.4,<5.0.0dev

test:
  imports:
    - bigquery_magics
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-magics
  summary: Google BigQuery magics for Jupyter and IPython
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
