{% set name = "bigquery-magics" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5df81e54ef3bc2f3a152c872db4c72f896e18243e99d0d09dd9f1a9ece44cf2d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - db-dtypes >=0.3.0,<2.0.0
    - google-cloud-bigquery-core >=3.13.0,<4.0.0
    - ipywidgets >=7.7.1
    - ipython >=7.23.1
    - ipykernel >=5.5.6
    - packaging >=20.0.0
    - pandas >=1.1.0
    - pyarrow >=3.0.0
    - pydata-google-auth >=1.5.0
    - tqdm >=4.7.4,<5.0.0

test:
  imports:
    - bigquery_magics
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/python-bigquery-magics
  summary: Google BigQuery magics for Jupyter and IPython
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
